name: cs231
channels:
  - conda-forge
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - ca-certificates
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - ipykernel=6.29.3=pyh3cd1d5f_0
  - ipython=8.22.2=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core
  - libffi
  - libsodium
  - libsqlite
  - libzlib
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl
  - packaging=24.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.0=pyhd8ed1ab_0
  - platformdirs=4.2.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - python=3.11
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.11=4_cp311
  - pyzmq
  - readline
  - setuptools=69.5.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk
  - tornado
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xz
  - zeromq
  - zipp=3.17.0=pyhd8ed1ab_0
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - cython==3.0.10
      - filelock==3.14.0
      - flatbuffers==24.3.25
      - fonttools==4.51.0
      - fsspec==2024.3.1
      - future==1.0.0
      - gast==0.5.4
      - google-pasta==0.2.0
      - grpcio==1.63.0
      - h5py==3.11.0
      - idna==3.7
      - imageio==2.34.1
      - jinja2==3.1.3
      - joblib==1.4.2
      - keras==3.3.3
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - libclang==18.1.1
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - mpmath==1.3.0
      - namex==0.0.8
      - networkx==3.3
      - numpy==1.26.4
      - opencv-python==4.9.0.80
      - opt-einsum==3.3.0
      - optree==0.11.0
      - pandas==2.2.2
      - pillow==10.3.0
      - protobuf==4.25.3
      - pyparsing==3.1.2
      - pypdf2==3.0.1
      - pytz==2024.1
      - requests==2.31.0
      - rich==13.7.1
      - scikit-image==0.23.2
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - sympy==1.12
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.1
      - tensorflow-io-gcs-filesystem==0.37.0
      - tensorflow-macos==2.16.1
      - tensorflow-metal==1.1.0
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tifffile==2024.5.10
      - torch==2.3.0
      - torchsummary==1.5.1
      - torchvision==0.18.0
      - tqdm==4.66.2
      - tzdata==2024.1
      - urllib3==2.2.1
      - werkzeug==3.0.2
      - wrapt==1.16.0
